### ISSUE TITLE
[Question] norm calculation

### ISSUE THREAD

**Issue by soup1997** [TimingSpace/MVOScaleRecovery#10]
Firstly, thanks for your great work.
In your paper, I can't understand the equation for calculating the normal vector and relative height.
What is the reason of normal vector obtained using inverse of 3 points in the plane rather than using cross product, and the relative height is obtained as the inverse of the size of the norm?

I will look forward to your reply
Thank you.

**Comment by TimingSpace** [comment]
Hi, thank you greatly for your interest!

Indeed, various other techniques, such as SVD decomposition , are available for determining the normal vector and height.

According to the method we used,  we solve \( An = h \), where:
- \( A \) is a 3x3 matrix constructed from the three points.
- \( n \) is the 3x1 normal vector.
- \( h \) is the 3x1 vector representing relative height, with identical elements.

Since the equation is under-constrained (3 equations, 4 unknowns), we set \( h \) to a vector of ones to simplify. This allows for the solution of the normal vector first, by solving \( An = [1, 1, 1]^T \). Then we find the normal vector \( n_s \) using the inverse of \( A \): \( n_s = A^{-1}[1, 1, 1]^T \).

After obtaining \( n_s \), which may not have the correct size (as its norm is not necessarily 1), we use the relationship \( An_s = [1, 1, 1] \) and denote the correctly sized normal vector as \( n_r \), with \( An_r = [h, h, h] \).

By comparing these two equations, we deduce that \(h / 1 = |n_r| / |n_s| \), which implies that the relative height \( h \) is the inverse of the norm of \( n_s \).

**Comment by soup1997** [comment]
Hello, Thank you for your answer.
I understand your intent and how the equation unfolds. 

I have another question about the your code. 
regarding the specific meaning of the value 0.3 in the provided code, it seems to be used as a threshold for determining when to adjust the self.scale variable during a scale recovery process.

how does it affect the scale recovery process and what is specific meaning of this value?

'''
if scale - self.scale > 0.3:
    self.scale += 0.3

elif scale - self.scale < -0.3:
    self.scale -= 0.3
    
else:
    self.scale = scale
'''

I will look forward to your reply.

**Comment by TimingSpace** [comment]
Hi, thank you once again for your interest! 

Yes, you are right! This parameter serves as a limit on the maximum change permissible in the scale obtained within a single interval, （where the interval duration is 100ms, assuming data collection occurs at a frequency of 10Hz). Physically, it represents a cap on the maximum acceleration within the current code.  
So, a larger value should be selected in scenarios where there are significant changes in the robot's speed and vice versa.
However, the value 0.3( |a| < 3m/s^2)  here is just an intuitive value that has not been tuned much.

Besides, should the initial results from the visual odometry maintain a relatively consistent scale, this parameter can also act as a maximum scale drift threshold within a single interval.
